'use client'

import { type FC, useState } from 'react'
import Link from 'next/link'
import { VillaCard, type Villa } from '@/components/ui'
import { cn } from '@/lib/utils'

// Mock data - será reemplazado por datos de Sanity CMS
const mockVillas: Villa[] = [
  {
    id: '1',
    slug: 'villa-coral-bay',
    title: 'Villa Coral Bay',
    location: 'Cap Cana',
    price_usd: 850000,
    area_sqm: 450,
    bedrooms: 4,
    bathrooms: 5,
    image_url: '/images/villas/coral-bay.jpg',
    status: 'available',
    is_render: true,
  },
  {
    id: '2',
    slug: 'villa-oceano',
    title: 'Villa Océano',
    location: 'Punta Cana Village',
    price_usd: 1200000,
    area_sqm: 580,
    bedrooms: 5,
    bathrooms: 6,
    image_url: '/images/villas/oceano.jpg',
    status: 'available',
    is_render: true,
  },
  {
    id: '3',
    slug: 'villa-palmera',
    title: 'Villa Palmera',
    location: 'Bávaro',
    price_usd: 650000,
    area_sqm: 380,
    bedrooms: 3,
    bathrooms: 4,
    image_url: '/images/villas/palmera.jpg',
    status: 'reserved',
    is_render: true,
  },
  {
    id: '4',
    slug: 'villa-arena',
    title: 'Villa Arena',
    location: 'Cap Cana',
    price_usd: 1500000,
    area_sqm: 720,
    bedrooms: 6,
    bathrooms: 7,
    image_url: '/images/villas/arena.jpg',
    status: 'available',
    is_render: true,
  },
  {
    id: '5',
    slug: 'villa-brisa',
    title: 'Villa Brisa',
    location: 'Punta Cana Village',
    price_usd: 920000,
    area_sqm: 490,
    bedrooms: 4,
    bathrooms: 5,
    image_url: '/images/villas/brisa.jpg',
    status: 'available',
    is_render: true,
  },
  {
    id: '6',
    slug: 'villa-sol',
    title: 'Villa Sol',
    location: 'Cap Cana',
    price_usd: 2100000,
    area_sqm: 850,
    bedrooms: 7,
    bathrooms: 8,
    image_url: '/images/villas/sol.jpg',
    status: 'available',
    is_render: true,
  },
]

export interface VillaGridProps {
  villas?: Villa[]
  locale?: 'es' | 'en'
  showFilters?: boolean
  limit?: number
  columns?: 2 | 3 | 4
}

type FilterLocation = 'all' | 'cap-cana' | 'punta-cana' | 'bavaro'
type FilterPrice = 'all' | '500k-1m' | '1m-2m' | '2m+'
type FilterStatus = 'all' | 'available' | 'reserved'

const content = {
  es: {
    title: 'Colección Exclusiva',
    subtitle: 'Villas diseñadas para el inversor exigente',
    filters: {
      location: 'Ubicación',
      price: 'Precio',
      status: 'Estado',
      all: 'Todos',
    },
    locations: {
      'cap-cana': 'Cap Cana',
      'punta-cana': 'Punta Cana Village',
      'bavaro': 'Bávaro',
    },
    prices: {
      '500k-1m': '$500K - $1M',
      '1m-2m': '$1M - $2M',
      '2m+': '+$2M',
    },
    statuses: {
      available: 'Disponible',
      reserved: 'Reservada',
    },
    noResults: 'No se encontraron villas con los filtros seleccionados.',
    disclaimer: 'Nota: Imágenes generadas mediante IA con fines conceptuales. Los acabados finales pueden variar.',
    viewAll: 'Ver toda la colección',
  },
  en: {
    title: 'Exclusive Collection',
    subtitle: 'Villas designed for the discerning investor',
    filters: {
      location: 'Location',
      price: 'Price',
      status: 'Status',
      all: 'All',
    },
    locations: {
      'cap-cana': 'Cap Cana',
      'punta-cana': 'Punta Cana Village',
      'bavaro': 'Bávaro',
    },
    prices: {
      '500k-1m': '$500K - $1M',
      '1m-2m': '$1M - $2M',
      '2m+': '$2M+',
    },
    statuses: {
      available: 'Available',
      reserved: 'Reserved',
    },
    noResults: 'No villas found with selected filters.',
    disclaimer: 'Disclaimer: Images generated by AI for conceptual purposes. Final finishes may vary.',
    viewAll: 'View full collection',
  },
}

export const VillaGrid: FC<VillaGridProps> = ({
  villas = mockVillas,
  locale = 'es',
  showFilters = true,
  limit,
  columns = 3,
}) => {
  const t = content[locale]
  const [filterLocation, setFilterLocation] = useState<FilterLocation>('all')
  const [filterPrice, setFilterPrice] = useState<FilterPrice>('all')
  const [filterStatus, setFilterStatus] = useState<FilterStatus>('all')

  // Apply filters
  let filteredVillas = villas

  if (filterLocation !== 'all') {
    const locationMap: Record<string, string> = {
      'cap-cana': 'Cap Cana',
      'punta-cana': 'Punta Cana Village',
      'bavaro': 'Bávaro',
    }
    filteredVillas = filteredVillas.filter(v => v.location === locationMap[filterLocation])
  }

  if (filterPrice !== 'all') {
    filteredVillas = filteredVillas.filter(v => {
      switch (filterPrice) {
        case '500k-1m': return v.price_usd >= 500000 && v.price_usd < 1000000
        case '1m-2m': return v.price_usd >= 1000000 && v.price_usd < 2000000
        case '2m+': return v.price_usd >= 2000000
        default: return true
      }
    })
  }

  if (filterStatus !== 'all') {
    filteredVillas = filteredVillas.filter(v => v.status === filterStatus)
  }

  // Apply limit
  if (limit) {
    filteredVillas = filteredVillas.slice(0, limit)
  }

  const columnClasses = {
    2: 'md:grid-cols-2',
    3: 'md:grid-cols-2 lg:grid-cols-3',
    4: 'md:grid-cols-2 lg:grid-cols-4',
  }

  return (
    <section className="section bg-roiba-arena">
      <div className="container-wide">
        {/* Section Header */}
        <div className="text-center mb-12">
          <span className="text-roiba-dorado text-sm font-semibold uppercase tracking-wider">
            {locale === 'es' ? 'Desde $500,000 USD' : 'From $500,000 USD'}
          </span>
          <h2 className="font-serif text-3xl md:text-4xl text-roiba-verde mt-3 mb-4">
            {t.title}
          </h2>
          <p className="text-roiba-verde/70 max-w-2xl mx-auto">
            {t.subtitle}
          </p>
          <div className="divider mt-6" />
        </div>

        {/* Filters */}
        {showFilters && (
          <div className="flex flex-wrap items-center justify-center gap-4 mb-10">
            {/* Location Filter */}
            <FilterSelect
              label={t.filters.location}
              value={filterLocation}
              onChange={(v) => setFilterLocation(v as FilterLocation)}
              options={[
                { value: 'all', label: t.filters.all },
                { value: 'cap-cana', label: t.locations['cap-cana'] },
                { value: 'punta-cana', label: t.locations['punta-cana'] },
                { value: 'bavaro', label: t.locations['bavaro'] },
              ]}
            />

            {/* Price Filter */}
            <FilterSelect
              label={t.filters.price}
              value={filterPrice}
              onChange={(v) => setFilterPrice(v as FilterPrice)}
              options={[
                { value: 'all', label: t.filters.all },
                { value: '500k-1m', label: t.prices['500k-1m'] },
                { value: '1m-2m', label: t.prices['1m-2m'] },
                { value: '2m+', label: t.prices['2m+'] },
              ]}
            />

            {/* Status Filter */}
            <FilterSelect
              label={t.filters.status}
              value={filterStatus}
              onChange={(v) => setFilterStatus(v as FilterStatus)}
              options={[
                { value: 'all', label: t.filters.all },
                { value: 'available', label: t.statuses.available },
                { value: 'reserved', label: t.statuses.reserved },
              ]}
            />
          </div>
        )}

        {/* Grid */}
        {filteredVillas.length > 0 ? (
          <div className={cn('grid gap-8', columnClasses[columns])}>
            {filteredVillas.map((villa) => (
              <Link key={villa.id} href={`/coleccion/${villa.slug}`}>
                <VillaCard villa={villa} />
              </Link>
            ))}
          </div>
        ) : (
          <div className="text-center py-16">
            <p className="text-roiba-verde/60">{t.noResults}</p>
          </div>
        )}

        {/* Disclaimer */}
        <p className="text-center text-xs text-roiba-verde/50 mt-10">
          {t.disclaimer}
        </p>

        {/* View All CTA */}
        {limit && villas.length > limit && (
          <div className="text-center mt-10">
            <Link 
              href="/coleccion"
              className="inline-flex items-center gap-2 text-roiba-dorado hover:text-roiba-dorado-oscuro font-medium transition-colors"
            >
              {t.viewAll}
              <ArrowRightIcon className="w-4 h-4" />
            </Link>
          </div>
        )}
      </div>
    </section>
  )
}

/* ===== FILTER SELECT ===== */
interface FilterSelectProps {
  label: string
  value: string
  onChange: (value: string) => void
  options: { value: string; label: string }[]
}

const FilterSelect: FC<FilterSelectProps> = ({ label, value, onChange, options }) => {
  return (
    <div className="flex items-center gap-2">
      <span className="text-sm text-roiba-verde/60">{label}:</span>
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="px-3 py-2 text-sm bg-white border border-roiba-verde/20 rounded-sm
                   text-roiba-verde focus:border-roiba-dorado focus:outline-none
                   cursor-pointer"
      >
        {options.map((opt) => (
          <option key={opt.value} value={opt.value}>
            {opt.label}
          </option>
        ))}
      </select>
    </div>
  )
}

/* ===== ICONS ===== */
const ArrowRightIcon: FC<{ className?: string }> = ({ className }) => (
  <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
    <path d="M5 12h14M12 5l7 7-7 7" />
  </svg>
)

export default VillaGrid
